-- 실습과제 9

-- 1. 대출을 받지 않은 고객의 ID를 출력하세요.
SELECT CUSTOMER_ID FROM CUSTOMERS
MINUS
SELECT CUSTOMER_ID FROM LOANS;

-- 2. 거래 테이블과 계좌 테이블에 공통적으로 존재하는 계좌 ID를 출력하시오
SELECT ACCOUNT_ID FROM TRANSACTIONS
INTERSECT
SELECT ACCOUNT_ID FROM ACCOUNTS;

-- 3. 대출 내역이 없는 지점 ID를 조회하시오
SELECT BRANCH_ID FROM BRANCHES
MINUS
SELECT BRANCH_ID FROM LOANS;
