-- 실습 7

-- 1. 각 지점의 이름과 대출 신청 고객의 정보 출력하기(대출 신청이 없는 지점도 포함)
-- 출력 : 지점 이름, 고객 이름, 대출금액
SELECT B.NAME, C.NAME, L.AMOUNT
FROM BRANCHES B
LEFT JOIN LOANS L
ON B.BRANCH_ID = L.BRANCH_ID
LEFT JOIN CUSTOMERS C
ON L.CUSTOMER_ID = C.CUSTOMER_ID;

-- 2.잔액이 50,000이상인 계좌를 가진 고객의 이름과 이메일 출력
SELECT C.NAME, C.EMAIL
FROM CUSTOMERS C
INNER JOIN ACCOUNTS A
ON C.CUSTOMER_ID = A.CUSTOMER_ID
WHERE A.BALANCE >= 50000;

-- 3. 대출 상태가 PENDING인 대출을 신청한 고객 이름과 대출 금액 조회
SELECT C.NAME, L.AMOUNT
FROM LOANS L
INNER JOIN CUSTOMERS C
ON C.CUSTOMER_ID = L.CUSTOMER_ID
WHERE L.STATUS = 'PENDING';
