-- 실습 11
-- 1. 쇼핑 카테고리 데이터의 순방향 계층 구조에서 동일한 부모를 가진 카테고리들에 대해 이름순으로 정렬하세요.
SELECT CATEGORY_ID, PARENT_CATEGORY_ID, CATEGORY_NAME, LEVEL
FROM SHOPPING_CATEGORIES
START WITH PARENT_CATEGORY_ID IS NULL
CONNECT BY PRIOR CATEGORY_ID = PARENT_CATEGORY_ID
ORDER SIBLINGS BY CATEGORY_NAME;

-- 2. 이름에 'Phones'가 포함된 카테고리와 해당 계층 구조를 순방향으로 출력하세요.
SELECT *
FROM SHOPPING_CATEGORIES
WHERE CATEGORY_NAME LIKE '%Phones%'
START WITH PARENT_CATEGORY_ID IS NULL
CONNECT BY PRIOR CATEGORY_ID = PARENT_CATEGORY_ID;

-- 3. 쇼핑 카테고리 데이터의 순방향 계층 구조에서 depth가 가장 깊은 level 값을 구하세요.
SELECT MAX(LEVEL)
FROM SHOPPING_CATEGORIES
START WITH PARENT_CATEGORY_ID IS NULL
CONNECT BY PRIOR CATEGORY_ID = PARENT_CATEGORY_ID;
